### ISSUE TITLE
this shows up on harmony island

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#156]
### What went wrong?

i didn't really get softlocked since map is clickable with other hot bar buttons

### How can I reproduce this?

i visit harmony island after reaching level 20

### What did the console output?

game.min.js:133577  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'worldPosition')
    at i.run (game.min.js:133577:58)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkRunes (game.min.js:132035:86)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkEntryPoint (game.min.js:137135:140)
    at i.<anonymous> (game.min.js:137126:41)
https://daboss7173.github.io/oldprodigy/bin/workers/NavMeshConstructor.js?v=1721088150581 not found

**Comment by XPMUser** [comment]
I also can't walk in this zone.

**Comment by strickjss-wq** [comment]
I keep having the same thing
