### ISSUE TITLE
Opponent's turn in 3.15.3

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#160]
### What went wrong?

Opponent's turn during battles froze 3.15.3

### How can I reproduce this?

Try doing battles in 3.15.3

### What did the console output?

game.min.js:92758  Uncaught TypeError: n is not a function
    at game.min.js:92758:63
    at t.Timer.update (phaser-e28c61a564.min.js:1:408745)
    at t.Time.update (phaser-e28c61a564.min.js:1:404532)
    at i.update (phaser-e28c61a564.min.js:1:173889)
    at i.update (game.min.js:10604:32)
    at t.RequestAnimationFrame.updateRAF (phaser-e28c61a564.min.js:1:375948)
    at window.requestAnimationFrame.forceSetTimeOut._onLoop (phaser-e28c61a564.min.js:1:375824)
    at pageScript.js:192:11

**Comment by Daboss7173** [comment]
This has been fixed. Thanks for reporting!
