### ISSUE TITLE
rune run wont work and i know why 

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#161]
### What went wrong?

rune run wont work and you know that

### How can I reproduce this?

click that blue crystal that lets you do rune runs

### What did the console output?

game.min.js:133951 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'worldPosition')
    at i.run (game.min.js:133951:58)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkRunes (game.min.js:132409:86)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkEntryPoint (game.min.js:137509:140)
    at i.<anonymous> (game.min.js:137500:41)

**Comment by XPMUser** [comment]
https://github.com/Daboss7173/Daboss7173.github.io/issues/159

**Comment by Toonigy** [comment]
game.min.js:133951 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'worldPosition')
    at i.run (game.min.js:133951:58)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkRunes (game.min.js:132409:86)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at i.checkEntryPoint (game.min.js:137509:140)
    at i.<anonymous> (game.min.js:137500:41)

**Comment by Daboss7173** [comment]
You've already made an issue about this. Next time, try just leaving a comment on the issue you've already made rather than making a new one. It's easier for both of us that way.
