### ISSUE TITLE
Crystal Caverns battle

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#162]
### What went wrong?

I'm stuck, but I didn't run out of hearts.

### How can I reproduce this?

Try battling a Grumpy Yeti in Crystal Caverns and cast Falling Star Smash on the crystals.

### What did the console output?

game.min.js:128626  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ID')
    at i.sendEvent (game.min.js:128626:29)
    at i.fsmCompleted (game.min.js:128653:49)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at game.min.js:12326:52
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at t.executeNext (game.min.js:3013:29)

**Comment by XPMUser** [comment]
The same problem goes for when trying to battle an upset worm.

**Comment by Daboss7173** [comment]
This has been fixed. Thanks for reporting!
