### ISSUE TITLE
Mine Cart tracks problem

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#163]
### What went wrong?

I tried to fix the tracks for the Mine Cart, but it froze the game.

### How can I reproduce this?

Try fixing the tracks for the Mine Cart that needs at least 4 tracks.

### What did the console output?

Uncaught TypeError: Cannot read properties of undefined (reading 'ID')
    at i.sendEvent (game.min.js:128626:29)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)
    at i.dispatch (game.min.js:1163:34)
    at game.min.js:129660:86
    at t.question (game.min.js:100274:4)
    at i.answerQuestion (game.min.js:129659:87)
    at i.openQuestion (game.min.js:129682:82)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at i.dispatch (phaser-e28c61a564.min.js:1:135836)

**Comment by Daboss7173** [comment]
This is fixed. Thanks for reporting.
