### ISSUE TITLE
3-15-3 Tutorial Problem

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#168]
### What went wrong?

When Noot tried to talk to me after I moved out of my house, the game froze.

### How can I reproduce this?

Click on the New Wizard button, create your wizard, click on the next button, and click on another next button 3 times.

### What did the console output?

Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at t.getPetEncounterByID (game.min.js:44705:36)
    at t.hasPetBeenEncountered (game.min.js:44703:43)
    at t.onPetEncountered (game.min.js:44716:19)
    at i.monsterEvent (game.min.js:99707:82)
    at i.addMonster (game.min.js:63833:49)
    at i.addMonster (game.min.js:8904:23)
    at i.start (game.min.js:112642:26)
    at i.start (game.min.js:63748:27)
    at t.SignalBinding.execute (phaser-e28c61a564.min.js:1:136779)
    at t.Signal.dispatch (phaser-e28c61a564.min.js:1:135836)

**Comment by Daboss7173** [comment]
Oh boy this issue's timing was just perfect. Like legit as I was getting ready to upload the fix for this very bug this report was made.

- but yeah I already saw the bug report made on the Discord server so I just patched it up right quick.
