### ISSUE TITLE
Battle Startup

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#210]
### What went wrong?

Starting a battle froze the game.

### How can I reproduce this?

Use 2015's saves for 2.6.0.

### What did the console output?

Uncaught TypeError: Cannot read properties of null (reading 'data')
    at t.getBattleItems (game.min.js:83042:46)
    at e.areItemsEnabled (game.min.js:6534:63)
    at e.refresh (game.min.js:6435:425)
    at game.min.js:2321:6
    at Array.forEach (<anonymous>)
    at e.onLoad (game.min.js:2320:26)
    at e.create (game.min.js:2240:10)
    at e.processConfigObj (game.min.js:2231:10)
    at e.update (game.min.js:2273:79)
    at i.Group.update (phaser.min.js:3:272197)

**Comment by Daboss7173** [comment]
> ### What went wrong?
> Starting a battle froze the game.
> 
> ### How can I reproduce this?
> Use 2015's saves for 2.6.0.
> 
> ### What did the console output?
> Uncaught TypeError: Cannot read properties of null (reading 'data') at t.getBattleItems (game.min.js:83042:46) at e.areItemsEnabled (game.min.js:6534:63) at e.refresh (game.min.js:6435:425) at game.min.js:2321:6 at Array.forEach () at e.onLoad (game.min.js:2320:26) at e.create (game.min.js:2240:10) at e.processConfigObj (game.min.js:2231:10) at e.update (game.min.js:2273:79) at i.Group.update (phaser.min.js:3:272197)

I tried that and it worked just fine. Don't know why this would happen to you.

Most likely has something to do with you using the same save for multiple different versions of the game, which you really aren't supposed to do as you can lose data. Either that or it's something else entirely that you completely overlooked.

I tried using multiple different "2015" versions (very vague but okay) and they all worked. Even tried to use older saves I had back from when I first made this site. Still no crash to be seen.

I'll close this for now, but if you have any updates (and figure out how this crash actually happened because it definitely wasn't what you said) you can totally re-open this and add a comment stating the new info.
