### ISSUE TITLE
Battle problem with Luma

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#211]
### What went wrong?

Luma in 1.60.0 made me stuck in a battle after casting spells.

### How can I reproduce this?

Do a battle with Luma on your team.

### What did the console output?

Phaser.Cache.getImage: Key "default-pet-133" not found in Cache.
getItem @ phaser.min.js:19
getImage @ phaser.min.js:19
loadTexture @ phaser.min.js:14
c.Component.Core.init @ phaser.min.js:14
c.Sprite @ phaser.min.js:14
Prodigy.Control.Sprite @ game.min.js:21290
sprite @ game.min.js:56384
setup @ game.min.js:33739
loadComplete @ game.min.js:57493
execute @ phaser.min.js:10
dispatch @ phaser.min.js:10
finishedLoading @ phaser.min.js:19
processLoadQueue @ phaser.min.js:19
start @ phaser.min.js:19
process @ game.min.js:57507
phaser.min.js:18  Uncaught TypeError: Cannot read properties of undefined (reading 'index')
    at c.FrameData.getFrameIndexes (phaser.min.js:18:30196)
    at c.AnimationManager.add (phaser.min.js:18:17890)
    at c.Group.callAll (phaser.min.js:11:12758)
    at Prodigy.Container.MonsterContainer.setup (game.min.js:33739:196)
    at Prodigy.Loader.loadComplete (game.min.js:57493:98)
    at c.SignalBinding.execute (phaser.min.js:10:28249)
    at c.Signal.dispatch (phaser.min.js:10:27301)
    at c.Loader.finishedLoading (phaser.min.js:19:23174)
    at c.Loader.processLoadQueue (phaser.min.js:19:22785)
    at c.Loader.start (phaser.min.js:19:21159)

**Comment by Daboss7173** [comment]
Luma and the other dragons weren't even finished in that version of the game. Cheating to obtain such pets isn't exactly a bug... it's just cheating.
