### ISSUE TITLE
Finneas is unviewable

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#236]
### What went wrong?

Finneas can't be viewed.

### Which version?

Version 1.70.0

### How can I reproduce this?

Go to the coliseum (contains Clankboot), click on him, click on the yes button and then click on the left or right arrow as many times as you can until you try to find Finneas (between Leena and Djinna).

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

[PRODIGY][ERROR] Item Data not found for type: affix ID: 
game.min.js:27163  Uncaught TypeError: Cannot read properties of null (reading 'type')
    at Prodigy.Entity.Equipment.calculateAffixBonus (game.min.js:27163:118)
    at Prodigy.Entity.Equipment.getHeartBonuses (game.min.js:27149:15)
    at e.getHeartBonus (game.min.js:27656:25)
    at e.getMaxHearts (game.min.js:27653:98)
    at e.getCurrentHearts (game.min.js:26632:233)
    at e.changeCurrentHearts (game.min.js:26635:16)
    at e.checkVersion (game.min.js:27501:107)
    at e.init (game.min.js:27484:8)
    at Prodigy.Menu.Coliseum.changeOpponent (game.min.js:31725:108)
    at Prodigy.Menu.Coliseum.shift (game.min.js:31722:317)

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
This has been fixed. Thanks for reporting!
