### ISSUE TITLE
Going home in 1-30-0

### ISSUE THREAD

**Issue by Ao28th28** [Daboss7173/Daboss7173.github.io#74]
What went wrong:
I get either a black rectangle or the game freezes unlike in Prodigy Reborn 1.0.
How can I replicate this:
Fix the going home problem  just like how it would be in Prodigy Reborn 1.0 for the 1-30-0 saves that have a going home error in yourgithubusername.github.io.
Console log output:
game.min.js:30149  Uncaught TypeError: Cannot read properties of undefined (reading 'active')
    at e.getBackground (game.min.js:30149:39)
    at e.create (game.min.js:49929:29)
    at c.StateManager.loadComplete (phaser.min.js:22:23055)
    at c.StateManager.preUpdate (phaser.min.js:22:19822)
    at c.Game.updateLogic (phaser.min.js:23:29027)
    at c.Game.update (phaser.min.js:23:28491)
    at c.RequestAnimationFrame.updateRAF (phaser.min.js:29:14931)
    at window.requestAnimationFrame.forceSetTimeOut._onLoop (phaser.min.js:29:14824)
e.getBackground @ game.min.js:30149
e.create @ game.min.js:49929
loadComplete @ phaser.min.js:22
preUpdate @ phaser.min.js:22
updateLogic @ phaser.min.js:23
update @ phaser.min.js:23
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)
updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29

![Screenshot 2023-09-24 195225](https://github.com/Daboss7173/Daboss7173.github.io/assets/122099346/c6d4d340-15d7-455b-b8d0-a9f9cecc26fc)

**Comment by Ao28th28** [comment]
At least Craftershaft's 1-30-0 didn't have this problem.

**Comment by Ao28th28** [comment]
Developer Tools console area keeps on spamming 'updateRAF @ phaser.min.js:29
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.min.js:29
requestAnimationFrame (async)'

**Comment by Ao28th28** [comment]
I just need '"bg":{"active":3,"own":[1]}' and then I'm good to go.
